
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="LGPLv3"

[[mods]] #mandatory

modId="verdant" #mandatory

version = "${version}"

displayName="Verdant" #mandatory

logoFile="icon.gif" #optional

credits="Ordana" #optional

authors="Ordana, Kayla_the_bee" #optional

itemIcon="verdant:template" #catalogue icon
description='''
Abundant foliage and greenery bring your world to life.
'''

[[dependencies.verdant]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.verdant]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.verdant]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.13.30,]"
    ordering="NONE"
    side="BOTH"
