
modLoader="javafml"

loaderVersion="[40,)"

license="LGPLv3"

[[mods]]

modId="verdant"

version = "${version}"

displayName="Verdant"

logoFile="icon.gif"

credits="Ordana"

authors="Ordana, Kayla_the_bee"

itemIcon="verdant:template"
description='''
Abundant foliage and greenery bring your world to life.
'''

[[dependencies.verdant]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.verdant]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.verdant]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.13.30,]"
    ordering="NONE"
    side="BOTH"
